[2015-12-18 12:09:42,987: WARNING/MainProcess] /u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2015-12-18 12:09:42,999: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
[2015-12-18 12:09:43,012: INFO/MainProcess] mingle: searching for neighbors
[2015-12-18 12:09:44,019: INFO/MainProcess] mingle: all alone
[2015-12-18 12:09:44,045: WARNING/MainProcess] w1@ckerns-rhel6.novalocal ready.
[2015-12-18 12:09:45,198: INFO/MainProcess] Events of group {task} enabled by remote.
[2015-12-18 12:10:18,990: INFO/MainProcess] Received task: glacier.get_vols[24520ddf-f8b8-43b0-a545-b256c74a0cc5]
[2015-12-18 12:10:19,059: INFO/MainProcess] Task glacier.get_vols[24520ddf-f8b8-43b0-a545-b256c74a0cc5] succeeded in 0.0627789410064s: [('ckerns-rhel6_DiffVol12',)]
[2015-12-18 12:22:09,444: INFO/MainProcess] sync with w2@ckerns-rhel6.novalocal
[2015-12-18 12:22:13,945: INFO/MainProcess] sync with w3@ckerns-rhel6.novalocal
[2015-12-18 12:22:17,481: INFO/MainProcess] sync with w4@ckerns-rhel6.novalocal
[2015-12-18 12:25:33,273: INFO/MainProcess] Received task: glacier.hash_file[72c5e7ce-c6fb-4846-813d-16e1f84d9b14]
[2015-12-18 12:25:33,275: INFO/MainProcess] Received task: glacier.hash_file[2824e0dd-579f-45ca-a684-cbda02475c10]
[2015-12-18 12:25:35,493: INFO/MainProcess] Task glacier.hash_file[72c5e7ce-c6fb-4846-813d-16e1f84d9b14] succeeded in 2.20553449297s: 'f52ebbee371cd5925908614357208a148cdeb933077aa82f002047fc26c7057b'
[2015-12-18 12:25:38,664: INFO/MainProcess] Task glacier.hash_file[2824e0dd-579f-45ca-a684-cbda02475c10] succeeded in 3.16996631899s: '8e2845b9a651e559581160f261a9069e32cfe76b94ccd84ee75782a04b0f0ca1'
[2015-12-18 12:27:35,871: INFO/MainProcess] Received task: glacier.hash_file[08afe2b7-e9d0-4d08-b145-14c9cb0c0180]
[2015-12-18 12:27:38,762: INFO/MainProcess] Task glacier.hash_file[08afe2b7-e9d0-4d08-b145-14c9cb0c0180] succeeded in 2.88823933899s: '35ee40034d2f2ee5d5e46c6efc9d62e1d1a0ae0f412baecbddbba6eabccb0a54'
[2015-12-18 12:37:05,503: INFO/MainProcess] Received task: glacier.upload_glacier[d0e8d001-5a52-4cc1-8925-11f2697f9266]
[2015-12-18 12:37:05,512: INFO/Worker-1] Found credentials in shared credentials file: ~/.aws/credentials
[2015-12-18 12:37:05,707: INFO/Worker-1] Starting new HTTPS connection (1): glacier.us-east-1.amazonaws.com
[2015-12-18 12:37:06,034: INFO/MainProcess] Task glacier.upload_glacier[d0e8d001-5a52-4cc1-8925-11f2697f9266] succeeded in 0.528051161091s: {u'archiveId':...
[2015-12-18 12:50:49,974: WARNING/MainProcess] /u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2015-12-18 12:50:51,051: WARNING/MainProcess] w1@ckerns-rhel6.novalocal ready.
[2015-12-21 11:05:47,459: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/worker/consumer.py", line 278, in start
    blueprint.start(self)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/worker/consumer.py", line 821, in start
    c.loop(*c.loop_args())
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/kombu/transport/base.py", line 164, in on_readable
    reader(loop)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/kombu/transport/base.py", line 146, in _read
    drain_events(timeout=0)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/connection.py", line 324, in drain_events
    return amqp_method(channel, args)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/connection.py", line 527, in _close
    self._x_close_ok()
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/connection.py", line 555, in _x_close_ok
    self._send_method((10, 51))
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/opt/rh/python27/root/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
[2015-12-21 11:05:47,735: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds...

[2015-12-21 11:05:49,783: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds...

[2015-12-21 11:05:53,828: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds...

[2015-12-22 15:14:26,686: WARNING/MainProcess] /u01/Djracula/.virtualenvs/bacula-glacier/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
[2015-12-22 15:14:27,794: WARNING/MainProcess] w1@ckerns-rhel6.novalocal ready.
